FROM openjdk:17
ADD target/JwelleryListingApp-0.0.1-SNAPSHOT.jar JwelleryListingApp-0.0.1-SNAPSHOT.jar
EXPOSE 8085
CMD ["/bin/bash","sleep 5000000000000000000000"]
ENTRYPOINT ["java","-jar","JwelleryListingApp-0.0.1-SNAPSHOT.jar"]
